package com.rdk.crime.domain;

import org.apache.commons.lang3.StringUtils;

public enum CrimeType {
	BATTERY("BATTERY"), THEFT("THEFT"), ROBBERY("ROBBERY"), CRIMINAL_DAMAGE(
			"CRIMINAL DAMAGE"), DECEPTIVE_PRACTICE("DECEPTIVE PRACTICE"), ASSAULT(
			"ASSAULT"), MOTOR_VEHICLE_THEFT("MOTOR VEHICLE THEFT"), NARCOTICS(
			"NARCOTICS"), INTERFERENCE_WITH_PUBLIC_OFFICER(
			"INTERFERENCE WITH PUBLIC OFFICER"), OTHER_OFFENSE("OTHER OFFENSE"), WEAPONS_VIOLATION(
			"WEAPONS VIOLATION"), ARSON("ARSON"), BURGLARY("BURGLARY"), CRIM_SEXUAL_ASSAULT(
			"CRIM SEXUAL ASSAULT"), CRIMINAL_TRESPASS("CRIMINAL TRESPASS"), PUBLIC_PEACE_VIOLATION(
			"PUBLIC PEACE VIOLATION"), OFFENSE_INVOLVING_CHILDREN(
			"OFFENSE INVOLVING CHILDREN"), HOMICIDE("HOMICIDE"), STALKING(
			"STALKING"), SEX_OFFENSE("SEX OFFENSE"), KIDNAPPING("KIDNAPPING"), PROSTITUTION(
			"PROSTITUTION"), GAMBLING("GAMBLING"), INTIMIDATION("INTIMIDATION"), NON_CRIMINAL(
			"NON-CRIMINAL"), LIQUOR_LAW_VIOLATION("LIQUOR LAW VIOLATION"), CONCEALED_CARRY_LICENSE_VIOLATION(
			"CONCEALED CARRY LICENSE VIOLATION"), NON_CRIMINAL2(
			"NON - CRIMINAL"), OBSCENITY("OBSCENITY"), HUMAN_TRAFFICKING(
			"HUMAN TRAFFICKING"), PUBLIC_INDECENCY("PUBLIC INDECENCY"), OTHER_NARCOTIC_VIOLATION(
			"OTHER NARCOTIC VIOLATION"), NON_CRIMINAL_SUBJECT_SPECIFIED(
			"NON-CRIMINAL (SUBJECT SPECIFIED)");

    private final String displayName;

    CrimeType( String displayName ) {
        this.displayName = displayName;
    }

	public String getDisplayName() {
		return this.displayName;
	}

    public boolean isSameType( String primaryTypeName ) {
        if ( StringUtils.isBlank( primaryTypeName ) ) {
            return false;
        }

        return primaryTypeName.equals( displayName );
    }
}
